slogan: The best in the west
# theme icons
theme:
- name: light
  title: Tema claro
  src: icons/themes/sun-fill.svg
  active: false
  id: sun-fill
- name: dark
  title: Tema oscuro
  src: icons/themes/moon-stars-fill.svg
  active: false
  id: moon-stars-fill
- name: auto
  title: Tema preferido
  src: icons/themes/circle-half.svg
  active: true
  id: circle-half
# https://schema.org/Organization
## JSON-LD
schemaType: "Organization"
  # schemaType: "Person"
contact:
  # https://schema.org/PostalAddress
  address:
  # first record is for schema
  - name: Address
    streetAddress: 
    - 48 Pirrama Rd
    addressLocality: Pyrmont
    addressRegion: NSW
    postalCode: 2009
    addressCountry: Australia
    # hasMap
    url: https://goo.gl/maps/2bHxJ3bfhtHtnx2b9
    geo: #coordinates 
    icon: icons/geo-alt.svg
    # icon: "#geo-alt"
    disable: false
  # postal address is just for contact details display
  # servicePostalAddress:
  #   postOfficeBoxNumber:
  #   addressLocality: Pyrmont
  #   addressRegion: NSW
  #   postalCode: 2009
  #   addressCountry: Australia

  openingHours:
  - name: Opening Hours
    icon: icons/clock.svg
    # icon: bi bi-clock
    hours:
    # date is ignored for display and schema
    - day: Monday
      open: 2021-01-01T09:00:00
      close: 2021-01-01T17:00:00
    - day: Tuesday
      open: 2021-01-01T09:00:00
      close: 2021-01-01T17:00:00
    - day: Saturday
      custom: By Appointment
    - day: Sunday
      custom: Closed
  telephone:
  # first record appears in schema data
  - name: Phone
    text: (02) 8004 3293
    url: "tel:+61280043293"
    icon: icons/phone.svg
    # icon: bi bi-phone
    disable: false
  # mobile
  # - text:
  #   url:
  #   icon: icons/bootstrap/telephone
  #   disable: false
  email: 
  - name: Email
    text: test@domain.com
    url: "mailto:test@domain.com"
    icon: icons/envelope.svg
    # icon: bi bi-envelope
    disable: false
    desc: Email Address
# only for contact details display
  extraItem:
  - name: Help Desk
    text: Help Desk
    url: helpdesk.com
    icon: 
    disable: true
social:
      whatsapp:
        title: "+56900000000"
        disable: false
        url: http://www.facebook.com/user
        icon: icons/whatsapp
# founder:
# foundingDate:
# foundingLocation:
logo: img/LOGO.png
